version: '3.8'
services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongodb.env
  redis:
    image: redis:7.0.2-alpine
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
  magiclinkredis:
    build: ./
    container_name: magic-link-redis
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/.env
    restart: 'on-failure'
    command: ['npm', 'run', 'dev']
    depends_on:
      - mongodb
      - redis
volumes:
  data: